name: Bug Report
description: Report a bug to help us improve
title: "bug: "
labels: [bug]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `./setup.sh`
        2. Open terminal
        3. Observe incorrect behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or logs if available.
      render: shell
    validations:
      required: false

  - type: input
    id: macos-version
    attributes:
      label: macOS Version
      description: Output of `sw_vers -productVersion`.
      placeholder: "15.3"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (shell version, terminal emulator, relevant config snippets, etc.).
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
